### ISSUE TITLE
Support for java form security

### ISSUE THREAD

**Issue by gokhanoner** [ingokegel/vaadin-loginform#10]
If you add a method to set if it's backed by java securtiy system, Spring-security etc, and send an actual response to ```j_security_check```, it can be much more useful. Below is a standard java login form, names and action are constant.

    <form method="POST" action="j_security_check">
    <input type="text" name="j_username">
    <input type="password" name="j_password">
    </form>

**Comment by ingokegel** [comment]
I don't have a spring security setup, but I don't see how Vaadin will display a login form for spring security. In any case, this is not something that I plan to do.
