### ISSUE TITLE
getContextPath() does not handle getContextPathFromService() returning null

### ISSUE THREAD

**Issue by manu-iyengar** [ingokegel/vaadin-loginform#12]
Hi Ingo,

I'm trying to use LoginForm in my app (for which thanks!, by the way, it looks great). However, the way I setup my login flow (deferred) means that VaadinServletService.getCurrentServletRequest() returns null at the moment at which I instantiate my LoginForm subclass (I'm outside the request/response loop) This causes a NPE in the getContextPath() method. Since the concerned methods are private, I can't override them to fix the issue in my subclass, any chance you can fix it in the original?

Thanks!

**Comment by ingokegel** [comment]
Thanks for reporting. Fixed in 0.6.1.

**Comment by manu-iyengar** [comment]
Thanks for the speedy fix! Works great!

Manu
