### ISSUE TITLE
Add additional Tenant-Field

### ISSUE THREAD

**Issue by kamuffe** [ingokegel/vaadin-loginform#13]
Hi.
Nice plugin. I have one enhancement ;)

My login form will have three textfields to login:
UserName
Password
Tenant-ID

Could you please add such an additional field which can optionally added to the login form?

Thanks in advance :)

**Comment by ingokegel** [comment]
You can add any number of fields to the login form by subclassing it.

**Comment by kamuffe** [comment]
Hi.

Thank you for your answer.

Sure, I can. But whats about the login method which does get only userName and password?

Thanks

**Comment by ingokegel** [comment]
You can save the reference to the field and call getValue() on it. It's still a regular Vaadin component.
