### ISSUE TITLE
Context path not working correctly in nested environments

### ISSUE THREAD

**Issue by tcoq** [ingokegel/vaadin-loginform#4]
Hi,
excellent Vaddin add on... Vaadin should take it to the core :-)

I figured out an improvement for nested servlet pathes. If you are running Vaadin in this way:

http://localhost/vaadin everythink is fine!

If you run it on a nested path like:

http://localhost/myapp/vaadin I ran into a 404 for /loginForm request.

Can you please change: (LoginForm.java)

        String contextPath = VaadinService.getCurrentRequest().getContextPath();
        if (contextPath.endsWith("/")) {
            contextPath = contextPath.substring(0, contextPath.length() - 1);
        }

To:

        String contextPath = Page.getCurrent().getLocation().getPath();
        if (contextPath.endsWith("/")) {
            contextPath = contextPath.substring(0, contextPath.length() - 1);
        }

With this little change it should also work for nested pathes...

Best regards
Steffen

**Comment by ingokegel** [comment]
Thank you, fixed in 0.4.4.
