### ISSUE TITLE
Unwanted click event on custom button click in same layout

### ISSUE THREAD

**Issue by sebgymn** [ingokegel/vaadin-loginform#5]
First of all, thanks for this wonderful addon, it works nicely. 

However, when I add a custom javascript button to the form and click it, your `loginButton` acts like it was clicked and calls `login(username, password)` method as if there was a click on login button, even if there wasn't. 

I have created a simple demo project for you to understand the issue. Please download and simply run `mvn vaadin:compile jetty:run` on <https://github.com/sebgymn/loginform-test> 

Thanks.

**Comment by ingokegel** [comment]
The add-on does not add listeners to any components other than the the text
field and the two standard buttons. Can you check if your button maybe
triggers the surrounding form?

2015-04-10 12:13 GMT+02:00 sebgymn <notifications@github.com>:

**Comment by sebgymn** [comment]
It does trigger form submission. [It seems that](http://stackoverflow.com/questions/11893573/what-triggers-an-html-form-to-submit) a `<button>` element should be added as `<button type="button">`.
