### ISSUE TITLE
NPE when refreshing the UI

### ISSUE THREAD

**Issue by lamirand-g** [ingokegel/vaadin-loginform#6]
Hi,

I got a NPE when I refresh the page;The UI is set up to preserve state on refresh. If I use restartApplication everything come back to normal.

Caused by: java.lang.NullPointerException
        at com.ejt.vaadin.loginform.LoginForm.init(LoginForm.java:153)
        at com.ejt.vaadin.loginform.LoginForm.attach(LoginForm.java:134)

Nice addon btw.

**Comment by ingokegel** [comment]
What Vaadin version do you use?

**Comment by lamirand-g** [comment]
I am using vaadin 7.4.6.
Le 28 mai 2015 3:06 PM, ingokegel <notifications@github.com> a écrit :What Vaadin version do you use?

**Comment by ingokegel** [comment]
Can you override attach of the component that contains the login form like
this:

    @Override
    public void attach() {
        super.attach();
        System.err.println("Page: " + Page.getCurrent());
        if (Page.getCurrent() != null) {
            System.err.println("Location: " +
Page.getCurrent().getLocation());
        }
    }

and let me know what the output is?

2015-05-28 15:14 GMT+02:00 lamirand-g <notifications@github.com>:

**Comment by lamirand-g** [comment]
I have tried many times but I am unable de reproduice the issue anymore...
Anyway thanks for your time, I will keep this in mind if the issue shows up.

**Comment by ingokegel** [comment]
I've changed the way to get the context path to make it more robust. It works now even if Page.getCurrent() is null.

**Comment by lamirand-g** [comment]
That's great! Thank you.
