### ISSUE TITLE
Memory leak on RequestHandler

### ISSUE THREAD

**Issue by fdreyfs** [ingokegel/vaadin-loginform#8]
Hi,
First, thank you for this great add-on.
I've been monitoring memory on my app which is using your addon.
I noticed that every time I do a refresh on my login page the new LoginForm created is preserved in the session.
This is because you add a RequestHandler which you don't remove when detaching the UI.
Setting the requestHandler as a private attribute and removing it by overriding detach() would solve this issue.

Thank you,

Best regards.

Fred

**Comment by ingokegel** [comment]
Thanks for the report, fixed in 0.5.1.
