### ISSUE TITLE
NullpointerException in Vaadin portlet

### ISSUE THREAD

**Issue by gorpet** [ingokegel/vaadin-loginform#9]
Not working for Vaadin portlet because VaadinServlet.getCurrent() returns null on line #192 in LoginForm.java. For Vaadin portlet implementation correct line to get context path would be: 
VaadinPortletService.getCurrentPortletRequest().getContextPath();

**Comment by ingokegel** [comment]
I've made changes to support portlets, but I cannot test the portlet functionality. Could you test it? For building the add-on just execute `gradlew` in the project root, the plugin will be built in build/libs.

**Comment by gorpet** [comment]
Hi!
Thanks for quick response and fix. I tested it on latest Liferay portal id it works.

Regards
